name: Sync to Gitee
on:
  push:
    branches:
      - main # 或者您的主分支名称
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: "git@github.com:Vivo-Max/app.git"
          destination-repo: "git@gitee.com:angxyaa/app.git"
