   name: Sync Gitee to GitHub

   on:
     schedule:
       - cron: '0 * * * *' # 每小时同步一次
     workflow_dispatch: # 手动触发

   jobs:
     sync:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout GitHub Repository
           uses: actions/checkout@v2
         
         - name: Sync with Gitee
           env:
             GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }} # Gitee 的访问令牌
           run: |
             git config --global user.email "1173287796@qq.com"
             git config --global user.name "angxyaa"

             # 克隆 Gitee 仓库
             git clone https://gitee.com/angxyaa/app.git
             cd app
             
             # 将更新拉取到 GitHub 仓库
             git remote add github https://github.com/Vivo-Max/app.git
             git fetch --all
             git merge github/main # 确保选择正确的分支
             git push github main
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
