name: Sync Gitee to GitHub

on:
  push:
    branches:
      - main  # 指定要同步的分支，如果需要同步其他分支，请更改

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Gitee repository
        uses: actions/checkout@v2
        with:
          repository: angxyaa/app  # Gitee 仓库名
          token: ${{ e146f86c622028b9b858caa21a7faf89 }}  # 使用 GitHub Secrets 存储的 Gitee 访问 token
          path: gitee-repo

      - name: Checkout GitHub repository
        uses: actions/checkout@v2
        with:
          repository: Vivo-Max/app  # GitHub 仓库名
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 默认 token
          path: github-repo

      - name: Sync changes to GitHub
        run: |
          cd gitee-repo
          # 添加 GitHub 远程仓库
          git remote add github ../github-repo
          # 拉取最新的 GitHub 变化
          git pull github main || true
          # 添加并提交更新的内容
          git push githu
