name: Sync with Gitee

on:
  schedule:
    - cron: '0 */12 * * *' # 每隔 12 小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Pull from Gitee
        run: |
          git config --global user.name "Vivo-Max"
          git config --global user.email "1173287796@qq.com"
          git remote add app git@gitee.com:angxyaa/app.git
          git fetch gitee
          git merge app/main || echo "No new changes to merge"

      - name: Push to GitHub
        run: |
          git push origin main
