name: Sync Gitee to GitHub  # 定义工作流的名称

on:
  schedule:
    - cron: '0 */12 * * *'  # 使用cron表达式设置每12小时触发一次
  push:
    branches:
      - main  # 当main分支有push事件时触发

jobs:
  sync:
    runs-on: ubuntu-latest  # 指定运行环境为最新的Ubuntu版本

    steps:
    - name: Checkout source repository  # 步骤名称：检出源代码仓库
      uses: actions/checkout@v2  # 使用actions/checkout@v2动作
      with:
        repository: vivo-max/app  # 指定要检出的GitHub仓库地址
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token进行身份验证

    - name: Sync to Gitee  # 步骤名称：同步到Gitee
      uses: wearerequired/git-mirror-action@v1.2.0  # 使用wearerequired/git-mirror-action@v1.2.0动作
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}  # 使用存储在Secrets中的Gitee私钥
      with:
        source-repo: git@github.com:vivo-max/app.git  # 指定源仓库地址（GitHub）
        destination-repo: git@gitee.com:angxyaa/app.git  # 指定目标仓库地址（Gitee）

    - name: Push changes to GitHub  # 步骤名称：推送更改到GitHub
      run: |
        git config --global user.email "1173287796@qq.com"  # 配置Git用户邮箱
        git config --global user.name "vivo-max"  # 配置Git用户名
        git remote add github git@github.com:vivo-max/app.git  # 添加GitHub远程仓库
        git push github main  # 推送更改到GitHub的main分支
